<?php
return [
    'adminEmail' => 'testingforproject0@gmail.com',
    'marveladminEmail' => 'rutusha.joshi@zenocraft.com',
    'supportEmail' => 'support@example.com',
    'senderEmail' => 'noreply@example.com',
    'senderName' => 'Example.com mailer',
    'site_url' => stripos($_SERVER['SERVER_PROTOCOL'], 'https') === true ? 'https://' . $_SERVER['HTTP_HOST'] : 'http://' . $_SERVER['HTTP_HOST'],
    'root_url' => stripos($_SERVER['SERVER_PROTOCOL'], 'https') === true ? 'https://' . $_SERVER['HTTP_HOST'] : 'http://' . $_SERVER['HTTP_HOST'] . "/marvelapp",
    'login_url' => '/marvelapp/admin/login',
    'frontend_login_url' => '/marvelapp/login',
    'user.passwordResetTokenExpire' => 3600,
    'userroles' => [
        'super_admin' => '1',
        'admin' => '2',
        'driver' => '3',
        'passanger' => '4',
    ],
    'user_status' => array('1' => 'Active', '0' => 'In-Active'),
    'user_status_value' => array('active' => '1', 'in_active' => '0'),
    'gender' => [
        '1' => 'Female',
        '2' => 'Male',
    ],
    'device_type_value' => ["1" => "android", "2" => "ios"],
    'bsVersion' => '4.x',
    'bsDependencyEnabled' => false,
    'super_admin_role_id' => '1',
    'administrator_role_id' => '2',
    'action' => ["1" => "delete", "2" => "archive", "3" => "un_archive"],
    'mail_sent' => ["false" => "0", "true" => "1"],
    'is_approve_vehicle' => ['1' => "Approve", "0" => "Decline","2"=>"Pending"],
    'is_approve_vehicle_value' => ['approve' => "1", "decline" => "0","pending"=>"2"],
    'device_type' => ["android" => "1", "ios" => "2"],
     'android_fcm_api_key' => 'AAAAy6A2HXo:APA91bFNAdf-gRAwul4F-JI7Bd68dpofkpCJWWC8EPzUCxVKn-xBHt1tD3C8pVXdHRbrSH92e8JWzQyt7MMJnIHn6P3Hn8Vd7hTWHOT8ai9-9UDNUfpPPP3R7mL2niLDfLn5tsJFpYqB',
];
